mkt=lm(Y~.,data=data)
residumkt=resid(mkt)
reskuadrat=residumkt^2
sigma.reskuadrat=sum(reskuadrat)
h1=(15/2+((2+2)/2))
h1 
urutan_1=arrange(data,reskuadrat)
data1=slice(urutan_1,1:10)
mkt_1=lm(Y~.,data=data1)
resmkt1=resid(mkt_1)
reskuarat1=resmkt1^2
sigma.reskuadrat1=sum(reskuarat1)
sigma.reskuadrat1
urutan_2=arrange(data1,reskuarat1)
h2=(10/2)+((2+2)/2)
h2
data2=slice(urutan_2,1:7)
mkt_2=lm(Y~.,data=data2)
resmkt2=resid(mkt_2)
reskuadrat2=resmkt2^2
sigma.reskuadrat2=sum(reskuadrat2)
sigma.reskuadrat2
